version: "3.8"

services:
  docker-postgres:
    container_name: docker-postgres
    image: postgres
    user: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_MULTIPLE_DATABASE: department_db,employee_db,organization_db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 3
    volumes:
      - ./docker-postgres-init.sql:/docker-entrypoint-initdb.d/docker-postgres-init.sql
    networks:
      springboot-microservice-net:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      springboot-microservice-net:

  service-registry:
    container_name: service-registry
    build:
      context: service-registry
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      springboot-microservice-net:

  config-server:
    container_name: config-server
    build:
      context: config-server
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - service-registry
    networks:
      springboot-microservice-net:

  api-gateway:
    container_name: api-gateway
    build:
      context: api-gateway
      dockerfile: Dockerfile
    ports:
      - "9191:9191"
    depends_on:
      - service-registry
      - employee-service
      - department-service
      - organization-service
    networks:
      springboot-microservice-net:

  department-service:
    container_name: department-service
    build:
      context: department-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    links:
      - docker-postgres
    depends_on:
      - config-server
      - docker-postgres
    restart: on-failure
    networks:
      springboot-microservice-net:

  employee-service:
    container_name: employee-service
    build:
      context: employee-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    links:
      - docker-postgres
    restart: on-failure
    depends_on:
      - config-server
      - docker-postgres
    networks:
      springboot-microservice-net:

  organization-service:
    container_name: organization-service
    build:
      context: organization-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    restart: on-failure
    links:
      - docker-postgres
    depends_on:
      - config-server
      - docker-postgres
    networks:
      springboot-microservice-net:

networks:
  springboot-microservice-net:
