version: "3.8"

services:
  docker-postgres:
    container_name: docker-postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DATABASE: department_db
      POSTGRES_USERNAME: postgres
    networks:
      springboot-microservice-net:

  department-service:
    container_name: department-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      springboot-microservice-net:
    restart: on-failure

networks:
  springboot-microservice-net: